### PR TITLE
fixed issues with nuget packages and added role provider

### PR DESCRIPTION
**Pull request by pcmantinker**
I fixed a few issues with the Nuget package configuration for the solution and I added my Neo4j custom role provider. I have not thoroughly tested every possible function in the role provider, but basic functions such as adding/removing a role or adding/removing a person from a role have been tested. I've also tested the IsUserInRole function as that was the main purpose for creating this custom provider.

### CODE REVIEW

**Comment by coreyauger** [comment]
Thanks Cameron.  I think the next big thing is OAuth.  I will test out your changes when i get a chance.

**Comment by pcmantinker** [comment]
No problem! I forgot to update your readme.md, but I can do so later if you like. The main thing to add would be the roleManager section in your web.config:

``` xml
<roleManager enabled="true" defaultProvider="Neo4JRoleProvider">
    <providers>
        <clear />
        <add name="Neo4JRoleProvider" type="Nextwave.Neo4J.Membership.Neo4JRolesProvider" connectionStringName="DefaultConnection" applicationName="app" />
    </providers>
</roleManager>
```

I am very interested in OAuth too. I will play with that some over the next week or two.

**Comment by coreyauger** [comment]
right on.. i will stick that in the readme.  Do you have a project that is live anywhere i can check out?  Pretty pumped that it is working out in the wild :)

**Comment by pcmantinker** [comment]
I've implemented your membership provider and my role provider on https://www.gamerfootprint.com. It's still a huge work in progress, but the registration and logging in works. I've also got basic profiles, although I wrote my own profile manager and I'm not using .NET's profile manager. You can also add your Xbox LIVE and PSN accounts to your profile :). For now, only Xbox LIVE games and achievements are capable of being shown, but PSN is soon to follow. Also, regarding account credentials for Xbox LIVE and PSN, I don't store passwords. I'm only capturing the oauth tokens for both services.

**Comment by coreyauger** [comment]
VERY interesting.
Are you on skype?  We should talk.  I have a project that I have stopped working on that was super fun.. check it out here: http://www.playquest.tv

We should see if you can use anything from that as it is literally doing nothing right now.. and was to cool to waste.  Let me know what you think.

**Comment by pcmantinker** [comment]
Yes, my Skype is pcmantinker. Look forward to chatting! And PlayQuest looks very nice!

**Pull request merged**
